// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "GetUsers",
    id: "595acce3-2bca-4328-9c7f-a39fa408664b",
    method: "GET",
    address: "https://reqres.in/api/users?page=2"
  });

  postman[Request]({
    name: "https://reqres.in/api/users",
    id: "26f5bbcf-7c94-442f-b657-92c6aa3996bb",
    method: "POST",
    address: "https://reqres.in/api/users",
    data: '{\n    "name": "morpheus",\n    "job": "leader"\n}'
  });

  postman[Request]({
    name: "https://reqres.in/api/users/2",
    id: "1a5cd9f5-64b7-493a-898d-6e602377b995",
    method: "PUT",
    address: "https://reqres.in/api/users/2",
    data: '{\n    "name": "morpheus",\n    "job": "zion resident"\n}'
  });

  postman[Request]({
    name: "https://reqres.in/api/users/12",
    id: "9e6b4ae4-ce3f-44de-934d-4d951d4f1b89",
    method: "DELETE",
    address: "https://reqres.in/api/users/12"
  });
}
